name: 🔬 Test zsbuild
on:
  push:
jobs:
  test:
    name: Rust tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-12
          - os: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.3'
      - uses: Swatinem/rust-cache@v1
      - name: Build bindings
        run: make
        working-directory: native
      - name: Run tests
        run: |
          cargo test -- --nocapture --test-threads=1
